version: '2'
services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    networks:
      - default_network
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    restart: always

  kafka:
    image: docker.io/bitnami/kafka:3.3
    build: .
    networks:
      - default_network
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

networks:
  default_network:
    name: default_network